Bugfix/characteristic column may contain space in sdrf file
ebi-gene-expression-group/db-scxa pull request #65
Opened 2023-05-31 10:14 UTC by lingyun1010

We have un-normalised sdrf column titles for factor and characteristics

2023-05-31 12:39 UTC, alfonsomunozpomer commented on bin/load_exp_design.sh
> +CharacteristicsArray=( Characteristics "Characteristics " )
I’m not the designated reviewer, but I think [pattern matching](https://www.linuxjournal.com/content/pattern-matching-bash) is a more robust solution.

2023-07-03 10:50 UTC, alfonsomunozpomer commented
Sorry I neglected this one for a while. Could you please add tests with their respective SDRF files in the `tests` directory?

2023-07-03 10:51 UTC, alfonsomunozpomer requested changes
All good, just missing tests to ensure SDRF files will be properly processed.

2023-08-22 10:21 UTC, ke4 approved these changes
LGTA 👍

2023-08-22 10:22 UTC, merged